"""Grad-CAM explainability for the Not Corgi classifier.

Per specifications.md section 4.1, Grad-CAM exists to verify the model attends
to tails, ears, and coat coloration rather than background artifacts. Section 7
requires that what Grad-CAM revealed be discussed in DESIGN.md.

This module is imported by both model/src/evaluate.py (for the written analysis)
and api/inference.py (to produce the heatmap the mobile app overlays), so the
heatmap the app displays is generated by the same code path that was validated
during evaluation.
"""

# TODO: imports


def compute_heatmap(model, image, class_index, last_conv_layer_name):
    """Return a Grad-CAM heatmap for one image and one target class.

    TODO: implement — gradients of the target class score with respect to the
    last convolutional feature map, channel-weighted and spatially pooled.
    """
    raise NotImplementedError


def overlay(image, heatmap, alpha=None):
    """Composite a heatmap onto the original image and return the result.

    TODO: implement.
    """
    raise NotImplementedError
