"""Grad-CAM explainability for the Not Corgi classifier.

Per specifications.md section 4.1, Grad-CAM exists to verify the model attends
to tails, ears, and coat coloration rather than background artifacts. Section 7
requires that what Grad-CAM revealed be discussed in DESIGN.md.

This module is imported by both model/src/evaluate.py (for the written analysis)
and api/inference.py (to produce the heatmap the mobile app overlays), so the
heatmap the app displays is generated by the same code path that was validated
during evaluation.
"""
import tensorflow as tf
import keras
import numpy as np
from PIL import Image


def compute_heatmap(model, image, class_index, last_conv_layer_name):
    """Return a Grad-CAM heatmap for one image and one target class.
    """
    base = model.get_layer("MobileNetV3Large")
    grad_model = keras.Model(base.inputs, [base.get_layer(last_conv_layer_name).output, base.output])
    gap = model.get_layer("global_average_pooling2d")
    dense = model.get_layer("dense")
    x = tf.convert_to_tensor(image[None].astype("float32"))
    with tf.GradientTape() as tape:
        conv_out, features = grad_model(x)
        tape.watch(conv_out)
        score = dense(gap(features))[:, class_index]
    gradients = tape.gradient(score, conv_out)
    weights = tf.reduce_mean(gradients, axis=(0, 1, 2))
    heatmap = tf.reduce_sum(conv_out[0] * weights, axis=-1)
    heatmap = tf.nn.relu(heatmap)
    return (heatmap / (tf.reduce_max(heatmap) + 1e-8)).numpy()


def overlay(image, heatmap, alpha=0.4):
    """Composite a heatmap onto the original image and return the result.
    """
    h, w = image.shape[:2]
    # .astype(np.uint8) rather than np.uint8(...): numpy's stubs type the latter
    # as a scalar constructor, so type checkers see a single uint8 being handed
    # to fromarray. Same result at runtime, correctly typed here.
    hm = np.asarray(
        Image.fromarray((heatmap * 255).astype(np.uint8))
        .resize((w, h), Image.Resampling.BILINEAR)
    ) / 255.0

    r = np.clip(1.5 - np.abs(4 * hm - 3), 0, 1)
    g = np.clip(1.5 - np.abs(4 * hm - 2), 0, 1)
    b = np.clip(1.5 - np.abs(4 * hm - 1), 0 , 1)
    colored = np.stack([r, g, b], axis=-1) * 255

    return (image * (1 - alpha) + colored * alpha).astype(np.uint8)
